module.exports = {
    InternalServerError: { code: 1001, message: "Something went wrong!" },
    UserUpdateFailed: {
        code: 1005,
        message: "Failed to update user details. Please try after sometime."
    },
    NotFound: { code: 1010, message: "Not found" },
    EmailNotValid: { code: 1010, message: "Email is not valid." },
    ValidOTP: { code: 1010, message: "Please Enter Valid OTP." },
    OTPExpire: { code: 1010, message: "OTP has expired." },
    OTPVerified: { code: 200, message: "OTP Verified Successfully." },
    PleaseVerifyOTP: { code: 1010, message: "Please Verify OTP." },
    OldPasswordNotMatch: { code: 1010, message: "Old Password Not Match." },
    mpinNotMatch: { code: 1010, message: "Your MPIN is not Match, Please try again." },
    emailVerified: { code: 200, message: "Email Verified." },
    OldMPINNotmatch: { code: 1010, message: "Old MPIN Not Match." },
    UserNotFound: { code: 1010, message: "User Not found" },
    AlreadyExist: { code: 1010, message: "Already Exist." },
    emailAlreadyExist: { code: 1010, message: "Email Already Exist." },
    InvalidCredential: { code: 1007, message: "Invalid username or password." },
    InvalidOldPassword: { code: 1007, message: "Invalid old password." },
    LoginSuccess: { code: 200, message: "Login successfully." },
    LoginAgain: { code: 200, message: "Please login." },
    Success: { code: 200, message: "Success." },
    updatedAkahuUserDetails: { code: 200, message: "Akahu User's Details Updated." },
    supportTicketCreate: { code: 200, message: "Support-Ticket Created Successfully." },
    supportTicketClosed: { code: 200, message: "Support-Ticket has been closed." },
    AccountDataSave: { code: 200, message: "Account Details Added." },
    AccountDataUpdate: { code: 200, message: "Account Details Updated." },
    AccountPrimary: { code: 200, message: "Account set as Primary Account." },
    AccountDelete: { code: 200, message: "Account Has removed Successfully." },
    DefaultPrimary: { code: 200, message: "Account is Default Primary Account." },
    passwordUpdated: { code: 200, message: "Password Updated." },
    mpinUpdated: { code: 200, message: "MPIN Updated." },
    monitizationDataAvailable: { code: 1010, message: "Already Monitization Data Available." },

    Fail: { code: 1010, message: "Fail....." },


    UserNotActivated: { code: 1012, message: "User is not activated yet." },
    SomethingWrong: { code: 1013, message: "Oops! something went wrong, please try again later." },
    MissingDeviceTokenParameter: { code: 1015, message: "Missing device token." },
    SubsciptionPlanExist: { code: 1011, message: "SubScription Plan Exist, Deactivate previous plan" },
}
