/**
 * set-env.js
 *
 * Writes `src/environments/environment.prod.ts` from environment variables
 * so that Vercel (or any CI system) can inject the API URL at build time
 * without committing secrets to source control.
 *
 * Environment variables consumed:
 *   VITE_API_URL       – base URL for the Express API  (default: https://desice.co.nz/v1/)
 *   VITE_UPLOADS_URL   – base URL for uploaded files   (default: https://desice.co.nz/uploads/)
 *   VITE_UPLOAD_FILE   – AWS Lambda upload endpoint    (optional, falls back to hardcoded value)
 *
 * Usage: node scripts/set-env.js
 */

const fs = require('fs');
const path = require('path');

const apiUrl        = process.env.VITE_API_URL      || 'https://desice.co.nz/v1/';
const uploadsUrl    = process.env.VITE_UPLOADS_URL  || 'https://desice.co.nz/uploads/';
const uploadFile    = process.env.VITE_UPLOAD_FILE  ||
  'https://17imjsjqd8.execute-api.eu-north-1.amazonaws.com/dev/desice-uploaded-files/';

const content = `// AUTO-GENERATED by scripts/set-env.js — do not edit by hand.
// Set VITE_API_URL / VITE_UPLOADS_URL / VITE_UPLOAD_FILE env vars to override.
export const environment = {
  production: true,
  apiUrl: '${apiUrl}',
  uploadsUrl: '${uploadsUrl}',
  uploadFile: '${uploadFile}',
};
`;

const dest = path.resolve(__dirname, '../src/environments/environment.prod.ts');
fs.writeFileSync(dest, content, 'utf8');
console.log(`[set-env] environment.prod.ts written`);
console.log(`  apiUrl:      ${apiUrl}`);
console.log(`  uploadsUrl:  ${uploadsUrl}`);
console.log(`  uploadFile:  ${uploadFile}`);
